uv run python -m autotrack.dl.train_trajectory_model \
  $(for d in datasets/train/sim_*; do echo --data-folder "$d"; done) \
  --out-dir models/trajectory_query_v1 \
  --epochs 20 \
  --batch-size 1 \
  --window-seconds 45 \
  --time-downsample 20 \
  --input-mode raw \
  --max-queries 96 \
  --hidden-dim 96 \
  --decoder-layers 1 \
  --num-heads 4 \
  --pooled-channels 8 \
  --pooled-time 128 \
  --trajectory-points 32 \
  --device mps \
  --no-object-weight 0.05 \
  --duplicate-loss-weight 0.2 \
  --duplicate-distance-tau 0.04 \
  --denoising-loss-weight 1.0 \
  --line-loss-weight 1.0 \
  --slope-smooth-loss-weight 0.25 \
  --denoising-queries 16 \
  --dn-point-noise 0.04 \
  --log-every 5
