#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/src"
PYTHON_BIN="${PYTHON_BIN:-$ROOT/.venv/bin/python3}"

RUN_DIR="${RUN_DIR:-$ROOT/results/vehicle_peakset_run}"
TRAIN_DIR="${TRAIN_DIR:-$RUN_DIR/peakguided_train_realshape_easy_completion}"
MODEL="${MODEL:-${1:-}}"
if [[ -z "$MODEL" ]]; then
  if [[ -f "$TRAIN_DIR/checkpoint_best.pt" ]]; then
    MODEL="$TRAIN_DIR/checkpoint_best.pt"
  elif [[ -f "$TRAIN_DIR/checkpoint_last.pt" ]]; then
    MODEL="$TRAIN_DIR/checkpoint_last.pt"
  else
    MODEL="$RUN_DIR/checkpoint_best.pt"
  fi
fi
OUT_DIR="${OUT_DIR:-${2:-$RUN_DIR/predict_true_realshape_cpu}}"
DATASET_DIR="${DATASET_DIR:-$ROOT/true_dataset/xi_gauss_50_120s_large/test}"
SAMPLE_INDEX="${SAMPLE_INDEX:-0}"
NUM_SAMPLES="${NUM_SAMPLES:-0}"
BATCH_SIZE="${BATCH_SIZE:-4}"
PLOT_SAMPLES="${PLOT_SAMPLES:-10}"
PLOT_STYLE="${PLOT_STYLE:-waveform}"

PREDICT_PROFILE="${PREDICT_PROFILE:-recall}"
case "$PREDICT_PROFILE" in
  strict)
    OBJECTNESS_DEFAULT=0.50
    COMPLETE_VALID_DEFAULT=0.55
    MIN_PEAK_SUPPORT_CHANNELS_DEFAULT=5
    MIN_PEAK_SUPPORT_RATIO_DEFAULT=0.30
    FUSED_MIN_ANCHOR_SCORE_DEFAULT=0.38
    MAX_TRACKS_DEFAULT=16
    SPEED_MIN_DEFAULT=40
    SPEED_MAX_DEFAULT=180
    SEGMENT_SPEED_MIN_DEFAULT=20
    SEGMENT_SPEED_MAX_DEFAULT=240
    MAX_LINE_RESIDUAL_DEFAULT=8.0
    MAX_ADJACENT_RESIDUAL_DEFAULT=6.0
    DEDUP_LINE_TOLERANCE_DEFAULT=0.6
    DEDUP_LOOSE_LINE_TOLERANCE_DEFAULT=1.0
    DEDUP_SPEED_TOLERANCE_DEFAULT=8.0
    MIN_TRACK_OBSERVED_RATIO_DEFAULT=0.25
    MIN_TRACK_TOTAL_SCORE_DEFAULT=8.0
    ;;
  balanced)
    OBJECTNESS_DEFAULT=0.35
    COMPLETE_VALID_DEFAULT=0.45
    MIN_PEAK_SUPPORT_CHANNELS_DEFAULT=3
    MIN_PEAK_SUPPORT_RATIO_DEFAULT=0.18
    FUSED_MIN_ANCHOR_SCORE_DEFAULT=0.34
    MAX_TRACKS_DEFAULT=20
    SPEED_MIN_DEFAULT=35
    SPEED_MAX_DEFAULT=200
    SEGMENT_SPEED_MIN_DEFAULT=15
    SEGMENT_SPEED_MAX_DEFAULT=280
    MAX_LINE_RESIDUAL_DEFAULT=10.0
    MAX_ADJACENT_RESIDUAL_DEFAULT=8.0
    DEDUP_LINE_TOLERANCE_DEFAULT=0.8
    DEDUP_LOOSE_LINE_TOLERANCE_DEFAULT=1.5
    DEDUP_SPEED_TOLERANCE_DEFAULT=10.0
    MIN_TRACK_OBSERVED_RATIO_DEFAULT=0.20
    MIN_TRACK_TOTAL_SCORE_DEFAULT=5.0
    ;;
  recall)
    OBJECTNESS_DEFAULT=0.25
    COMPLETE_VALID_DEFAULT=0.35
    MIN_PEAK_SUPPORT_CHANNELS_DEFAULT=2
    MIN_PEAK_SUPPORT_RATIO_DEFAULT=0.10
    FUSED_MIN_ANCHOR_SCORE_DEFAULT=0.30
    MAX_TRACKS_DEFAULT=24
    SPEED_MIN_DEFAULT=25
    SPEED_MAX_DEFAULT=220
    SEGMENT_SPEED_MIN_DEFAULT=10
    SEGMENT_SPEED_MAX_DEFAULT=320
    MAX_LINE_RESIDUAL_DEFAULT=20.0
    MAX_ADJACENT_RESIDUAL_DEFAULT=15.0
    DEDUP_LINE_TOLERANCE_DEFAULT=1.0
    DEDUP_LOOSE_LINE_TOLERANCE_DEFAULT=2.0
    DEDUP_SPEED_TOLERANCE_DEFAULT=12.0
    MIN_TRACK_OBSERVED_RATIO_DEFAULT=0.15
    MIN_TRACK_TOTAL_SCORE_DEFAULT=4.0
    ;;
  *)
    echo "unknown PREDICT_PROFILE=$PREDICT_PROFILE, expected strict|balanced|recall" >&2
    exit 2
    ;;
esac

OBJECTNESS_THRESHOLD="${OBJECTNESS_THRESHOLD:-$OBJECTNESS_DEFAULT}"
COMPLETE_VALID_THRESHOLD="${COMPLETE_VALID_THRESHOLD:-$COMPLETE_VALID_DEFAULT}"
OBSERVED_THRESHOLD="${OBSERVED_THRESHOLD:-0.45}"
MIN_VISIBLE_CHANNELS="${MIN_VISIBLE_CHANNELS:-5}"
MIN_PEAK_SUPPORT_CHANNELS="${MIN_PEAK_SUPPORT_CHANNELS:-$MIN_PEAK_SUPPORT_CHANNELS_DEFAULT}"
MIN_PEAK_SUPPORT_RATIO="${MIN_PEAK_SUPPORT_RATIO:-$MIN_PEAK_SUPPORT_RATIO_DEFAULT}"
FUSED_MIN_ANCHOR_SCORE="${FUSED_MIN_ANCHOR_SCORE:-$FUSED_MIN_ANCHOR_SCORE_DEFAULT}"
MAX_TRACKS="${MAX_TRACKS:-$MAX_TRACKS_DEFAULT}"
SNAP_TO_CANDIDATES="${SNAP_TO_CANDIDATES:-0}"
SNAP_TOLERANCE_S="${SNAP_TOLERANCE_S:-0.25}"
POSTPROCESS="${POSTPROCESS:-1}"
POSTPROCESS_REFIT_MISSING="${POSTPROCESS_REFIT_MISSING:-1}"
POSTPROCESS_REFIT_OBSERVED="${POSTPROCESS_REFIT_OBSERVED:-0}"
POSTPROCESS_VALIDATE_OBSERVED_ONLY="${POSTPROCESS_VALIDATE_OBSERVED_ONLY:-1}"
SPEED_MIN_KMH="${SPEED_MIN_KMH:-$SPEED_MIN_DEFAULT}"
SPEED_MAX_KMH="${SPEED_MAX_KMH:-$SPEED_MAX_DEFAULT}"
SEGMENT_SPEED_MIN_KMH="${SEGMENT_SPEED_MIN_KMH:-$SEGMENT_SPEED_MIN_DEFAULT}"
SEGMENT_SPEED_MAX_KMH="${SEGMENT_SPEED_MAX_KMH:-$SEGMENT_SPEED_MAX_DEFAULT}"
MAX_LINE_RESIDUAL_S="${MAX_LINE_RESIDUAL_S:-$MAX_LINE_RESIDUAL_DEFAULT}"
MAX_ADJACENT_RESIDUAL_S="${MAX_ADJACENT_RESIDUAL_S:-$MAX_ADJACENT_RESIDUAL_DEFAULT}"
DEDUP_LINE_TOLERANCE_S="${DEDUP_LINE_TOLERANCE_S:-$DEDUP_LINE_TOLERANCE_DEFAULT}"
DEDUP_LOOSE_LINE_TOLERANCE_S="${DEDUP_LOOSE_LINE_TOLERANCE_S:-$DEDUP_LOOSE_LINE_TOLERANCE_DEFAULT}"
DEDUP_SPEED_TOLERANCE_KMH="${DEDUP_SPEED_TOLERANCE_KMH:-$DEDUP_SPEED_TOLERANCE_DEFAULT}"
MIN_TRACK_OBSERVED_RATIO="${MIN_TRACK_OBSERVED_RATIO:-$MIN_TRACK_OBSERVED_RATIO_DEFAULT}"
MIN_TRACK_TOTAL_SCORE="${MIN_TRACK_TOTAL_SCORE:-$MIN_TRACK_TOTAL_SCORE_DEFAULT}"
ANCHOR_PATH_REFINE="${ANCHOR_PATH_REFINE:-1}"
ANCHOR_PATH_TOP_K="${ANCHOR_PATH_TOP_K:-5}"
ANCHOR_PATH_TRANSITION_WEIGHT="${ANCHOR_PATH_TRANSITION_WEIGHT:-8.0}"
ANCHOR_PATH_SECOND_DIFF_WEIGHT="${ANCHOR_PATH_SECOND_DIFF_WEIGHT:-2.5}"
ANCHOR_PATH_BASELINE_WEIGHT="${ANCHOR_PATH_BASELINE_WEIGHT:-1.5}"
ANCHOR_PATH_ROBUST_BASELINE="${ANCHOR_PATH_ROBUST_BASELINE:-1}"
ANCHOR_PATH_ROBUST_BASELINE_WEIGHT="${ANCHOR_PATH_ROBUST_BASELINE_WEIGHT:-2.5}"
ANCHOR_PATH_ROBUST_BASELINE_TOLERANCE_S="${ANCHOR_PATH_ROBUST_BASELINE_TOLERANCE_S:-2.0}"
ANCHOR_PATH_ROBUST_BASELINE_MIN_SUPPORT="${ANCHOR_PATH_ROBUST_BASELINE_MIN_SUPPORT:-4}"
ANCHOR_PATH_MAX_ADJACENT_JUMP_S="${ANCHOR_PATH_MAX_ADJACENT_JUMP_S:-8.0}"
OBSERVED_OUTLIER_REPAIR="${OBSERVED_OUTLIER_REPAIR:-1}"
OBSERVED_OUTLIER_RESIDUAL_S="${OBSERVED_OUTLIER_RESIDUAL_S:-4.0}"
OBSERVED_OUTLIER_ADJACENT_S="${OBSERVED_OUTLIER_ADJACENT_S:-6.0}"
POSTPROCESS_REPAIR_OUTLIER_POINTS="${POSTPROCESS_REPAIR_OUTLIER_POINTS:-1}"
POSTPROCESS_DROP_POINT_RESIDUAL_S="${POSTPROCESS_DROP_POINT_RESIDUAL_S:-8.0}"
POSTPROCESS_REPAIR_POINT_RESIDUAL_S="${POSTPROCESS_REPAIR_POINT_RESIDUAL_S:-4.0}"
POSTPROCESS_DROP_POINT_SECOND_DIFF_S="${POSTPROCESS_DROP_POINT_SECOND_DIFF_S:-6.0}"
POSTPROCESS_EXTEND_MISSING="${POSTPROCESS_EXTEND_MISSING:-1}"
POSTPROCESS_EXTEND_MAX_CHANNELS="${POSTPROCESS_EXTEND_MAX_CHANNELS:-8}"
POSTPROCESS_EXTEND_MIN_OBSERVED="${POSTPROCESS_EXTEND_MIN_OBSERVED:-4}"

export PYTHONPATH="$SRC${PYTHONPATH:+:$PYTHONPATH}"
if [[ ! -f "$MODEL" ]]; then
  echo "checkpoint not found: $MODEL" >&2
  exit 2
fi
mkdir -p "$OUT_DIR"

ARGS=(
  --model "$MODEL"
  --dataset-dir "$DATASET_DIR"
  --out-dir "$OUT_DIR"
  --device cpu
  --sample-index "$SAMPLE_INDEX"
  --num-samples "$NUM_SAMPLES"
  --batch-size "$BATCH_SIZE"
  --plot-samples "$PLOT_SAMPLES"
  --plot-style "$PLOT_STYLE"
  --objectness-threshold "$OBJECTNESS_THRESHOLD"
  --complete-valid-threshold "$COMPLETE_VALID_THRESHOLD"
  --observed-threshold "$OBSERVED_THRESHOLD"
  --min-visible-channels "$MIN_VISIBLE_CHANNELS"
  --min-peak-support-channels "$MIN_PEAK_SUPPORT_CHANNELS"
  --min-peak-support-ratio "$MIN_PEAK_SUPPORT_RATIO"
  --fused-min-anchor-score "$FUSED_MIN_ANCHOR_SCORE"
  --max-tracks "$MAX_TRACKS"
  --dedup-line-tolerance-s "$DEDUP_LINE_TOLERANCE_S"
  --dedup-loose-line-tolerance-s "$DEDUP_LOOSE_LINE_TOLERANCE_S"
  --dedup-speed-tolerance-kmh "$DEDUP_SPEED_TOLERANCE_KMH"
  --min-track-observed-ratio "$MIN_TRACK_OBSERVED_RATIO"
  --min-track-total-score "$MIN_TRACK_TOTAL_SCORE"
  --anchor-path-top-k "$ANCHOR_PATH_TOP_K"
  --anchor-path-transition-weight "$ANCHOR_PATH_TRANSITION_WEIGHT"
  --anchor-path-second-diff-weight "$ANCHOR_PATH_SECOND_DIFF_WEIGHT"
  --anchor-path-baseline-weight "$ANCHOR_PATH_BASELINE_WEIGHT"
  --anchor-path-robust-baseline-weight "$ANCHOR_PATH_ROBUST_BASELINE_WEIGHT"
  --anchor-path-robust-baseline-tolerance-s "$ANCHOR_PATH_ROBUST_BASELINE_TOLERANCE_S"
  --anchor-path-robust-baseline-min-support "$ANCHOR_PATH_ROBUST_BASELINE_MIN_SUPPORT"
  --anchor-path-max-adjacent-jump-s "$ANCHOR_PATH_MAX_ADJACENT_JUMP_S"
  --observed-outlier-residual-s "$OBSERVED_OUTLIER_RESIDUAL_S"
  --observed-outlier-adjacent-s "$OBSERVED_OUTLIER_ADJACENT_S"
  --postprocess-drop-point-residual-s "$POSTPROCESS_DROP_POINT_RESIDUAL_S"
  --postprocess-repair-point-residual-s "$POSTPROCESS_REPAIR_POINT_RESIDUAL_S"
  --postprocess-drop-point-second-diff-s "$POSTPROCESS_DROP_POINT_SECOND_DIFF_S"
  --postprocess-extend-max-channels "$POSTPROCESS_EXTEND_MAX_CHANNELS"
  --postprocess-extend-min-observed "$POSTPROCESS_EXTEND_MIN_OBSERVED"
  --snap-tolerance-s "$SNAP_TOLERANCE_S"
  --speed-min-kmh "$SPEED_MIN_KMH"
  --speed-max-kmh "$SPEED_MAX_KMH"
  --segment-speed-min-kmh "$SEGMENT_SPEED_MIN_KMH"
  --segment-speed-max-kmh "$SEGMENT_SPEED_MAX_KMH"
  --max-line-residual-s "$MAX_LINE_RESIDUAL_S"
  --max-adjacent-residual-s "$MAX_ADJACENT_RESIDUAL_S"
)

if [[ "$ANCHOR_PATH_REFINE" == "1" ]]; then
  ARGS+=(--anchor-path-refine)
else
  ARGS+=(--no-anchor-path-refine)
fi
if [[ "$ANCHOR_PATH_ROBUST_BASELINE" == "1" ]]; then
  ARGS+=(--anchor-path-robust-baseline)
else
  ARGS+=(--no-anchor-path-robust-baseline)
fi
if [[ "$OBSERVED_OUTLIER_REPAIR" == "1" ]]; then
  ARGS+=(--observed-outlier-repair)
else
  ARGS+=(--no-observed-outlier-repair)
fi
if [[ "$SNAP_TO_CANDIDATES" == "1" ]]; then
  ARGS+=(--snap-to-candidates)
else
  ARGS+=(--no-snap-to-candidates)
fi
if [[ "$POSTPROCESS" == "1" ]]; then
  ARGS+=(--postprocess)
else
  ARGS+=(--no-postprocess)
fi
if [[ "$POSTPROCESS_REFIT_MISSING" == "1" ]]; then
  ARGS+=(--postprocess-refit-missing)
else
  ARGS+=(--no-postprocess-refit-missing)
fi
if [[ "$POSTPROCESS_REFIT_OBSERVED" == "1" ]]; then
  ARGS+=(--postprocess-refit-observed)
else
  ARGS+=(--no-postprocess-refit-observed)
fi
if [[ "$POSTPROCESS_VALIDATE_OBSERVED_ONLY" == "1" ]]; then
  ARGS+=(--postprocess-validate-observed-only)
else
  ARGS+=(--no-postprocess-validate-observed-only)
fi
if [[ "$POSTPROCESS_REPAIR_OUTLIER_POINTS" == "1" ]]; then
  ARGS+=(--postprocess-repair-outlier-points)
else
  ARGS+=(--no-postprocess-repair-outlier-points)
fi
if [[ "$POSTPROCESS_EXTEND_MISSING" == "1" ]]; then
  ARGS+=(--postprocess-extend-missing)
else
  ARGS+=(--no-postprocess-extend-missing)
fi

"$PYTHON_BIN" scripts/predict_vehicle_peak_set_real.py "${ARGS[@]}"
